### ISSUE TITLE
Client ID is required. (riga 43, file "Utilities", progetto "OAuth2")

### ISSUE THREAD

**Issue by AlessioFedi** [Spencer-Easton/Domain-Email-Signatures#2]
Hi Spencer,
I have correctly set up your information (library, API enabled, Oauth Web Application).
I have put a ClientID, ClientSecret and ProjectKey in AdminOauth2.gs
I have put var organization and domainName in code.gs
I have set my email in code.gs
But when I run a "doGet" script in code.gs is returned error 
Client ID is required. (riga 43, file "Utilities", progetto "OAuth2")
Why ?

**Comment by Spencer-Easton** [comment]
Share the project real quick and ill take a look

**Comment by AlessioFedi** [comment]
Sorry, but how can I share my script with you ?


Alessio Fedi

Responsabile Organizzazione



Corso S.Fedi 25 - 51100 Pistoia
Tel. 0573 974064 - Cell. 3346209921
Fax 0573 993090
alessio.fedi@bancadipistoia.it
organizzazione@bancadipistoia.it

AVVISO DI RISERVATEZZA - Il testo e gli eventuali documenti trasmessi
contengono informazioni riservate al destinatario indicato. La seguente
e-mail è confidenziale e la sua riservatezza è tutelata legalmente dalle
normative vigenti. La lettura, copia od altro uso non autorizzato o
qualsiasi alterazione derivante dalla conoscenza di queste informazioni
sono rigorosamente vietate. Se si ritiene di non essere il destinatario di
questa mail, o se si è ricevuto questa mail per errore, si prega di darne
immediata comunicazione al mittente e di provvedere immediatamente alla sua
distruzione.

2015-04-13 17:17 GMT+02:00 Spencer-Easton <notifications@github.com>:

**Comment by Spencer-Easton** [comment]
seaston@ccsknights.org

The share button is in the top right of the script.

________________________________
