### ISSUE TITLE
with the v21 apps-script-oauth2 seems not working anymore

### ISSUE THREAD

**Issue by Giorj73** [Spencer-Easton/Domain-Email-Signatures#3]
Hi
I started to have some errors on my webapp that is using the
apps-script-oauth2
with part of the code from your code,
but because the deprecation of .setPorjectKey('xxx')
I switch to v21
and is not working anymore
now I have 
Authorization is required to perform that action.
Access not granted or expired. (line 352, file "Service", project "OAuth2")

**Comment by Spencer-Easton** [comment]
This method has been depreciated by google. 
https://apps-apis.google.com/a/feeds/emailsettings/2.0/ 

Use the Gmail api to set signatures.
https://developers.google.com/gmail/api/v1/reference/users/settings/sendAs/patch

**Comment by Giorj73** [comment]
Yes but now the scopes are two
Should I set instead
. setScope('https://apps-apis.google.com/a/feeds/emailsettings/2.0/')

.setScope('https://www.googleapis.com/auth/gmail.settings.basic https://www.googleapis.com/auth/gmail.settings.sharing')

Same error (changed also under the security panel in the console)

**Comment by Spencer-Easton** [comment]
OK sorry I'll be more explicit. I'm not updating this repo as this method shouldn't be used any more.  If you have an issue with the OAuth2 library that is maintained at:
https://github.com/googlesamples/apps-script-oauth2

**Comment by Giorj73** [comment]
fyi I just switch to a Service Account, and is working again
